pilot:
  enabled: true

gateways:
  enabled: false

security:
  enabled: true
  createMeshPolicy: false

sidecarInjectorWebhook:
  enabled: true

galley:
  enabled: true
  configSink:
    tag: "__TCC__"
    token: ""

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

prometheus:
  enabled: false

oap:
  enabled: true
  tag: "v1.0.build.1581046"
  token: ""
  elasticsearch:
    host: "__HOST__"
    port: 8443

regsource:
  enabled: true
  tag: "__TCC__"
  token: ""

global:
  tcc:
    enabled: true
    host: "__HOST__"
    port: 8443
    tenant: "__TENANT__"
    cluster: "__CLUSTER__"
    environment: "__ENV__"

  hub: "__HUB__"
  tag: "__ISTIO__"
  controlPlaneSecurityEnabled: true
  disablePolicyChecks: true
  enableTracing: false
  configValidation: false
  defaultPodDisruptionBudget:
    enabled: false

  proxy:
    envoyAccessLogService:
      enabled: true
      host: oap.istio-system
      port: 11800

  mtls:
    enabled: false

  outboundTrafficPolicy:
    mode: ALLOW_ANY

  configRootNamespace: istio-config
  defaultConfigVisibilitySettings:
  - '.'
