pilot:
  traceSampling: 100.0
  enabled: true
  env:
    PILOT_PUSH_THROTTLE: 100
    HTTP10: "true"
    PILOT_ENABLE_MYSQL_FILTER: "false"
    PILOT_SCOPE_GATEWAY_TO_NAMESPACE: "true"

gateways:
  enabled: true

  istio-ingressgateway:
    enabled: false

  # VM gateway to service external VM workloads
  vmgateway:
    enabled: true
    type: LoadBalancer
    labels:
      app: vmgateway
      tcc: vmgateway
    sds:
      enabled: true
      image: node-agent-k8s
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
    env:
      ISTIO_META_ROUTER_MODE: ""
    ports:
    - port: 15011
      targetPort: 15011
      name: tcp-pilot-grpc
    - port: 8060
      targetPort: 8060
      name: tcp-citadel-grpc
    - port: 11800
      targetPort: 11800
      name: tcp-oap-grpc
    - port: 9411
      targetPort: 9411
      name: tcp-tracing-grpc

security:
  enabled: true
  createMeshPolicy: false

sidecarInjectorWebhook:
  enabled: true

galley:
  enabled: false

tsbd:
  enabled: true
  tag: "__TCC__"

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

prometheus:
  enabled: false

tracing:
  enabled: true
  elasticsearch:
    host: "__HOST__"
    port: 8443
  zipkin:
    #token: ""
    env:
      STORAGE_TYPE: "elasticsearch"
      # Zipkin sends to local envoy which forwards to TCC elastic search.
      ES_HOSTS: "http://127.0.0.1:9200"

zipkin:
  hub: "__HUB__"

oap:
  enabled: true
  # Set by bash scripts in deploy folder of tetrate repo 
  tag: "__OAP__"
  token: ""
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
  elasticsearch:
    host: "__HOST__"
    port: 8443
  analysis: reg-agent-mesh
  externalServices:
    # For SPM metadata service.
    metadata:
      enabled: false
    # For SPM configuration service (DCS).
    configuration:
      enabled: false
      clusterName: default
    # Optionally add (default) webhook uri here.
    webhook:
      uri: ""

global:
  tcc:
    enabled: true
    host: "__HOST__"
    port: 8443
    tenant: "__TENANT__"
    cluster: "__CLUSTER__"
    environment: "__ENV__"

  hub: "__HUB__"
  tag: "__ISTIO__"
  controlPlaneSecurityEnabled: true
  disablePolicyChecks: true
  enableTracing: true
  configValidation: false
  defaultPodDisruptionBudget:
    enabled: false

  proxy:
    envoyAccessLogService:
      enabled: true
      host: oap.istio-system
      port: 11800
  proxy_init:
    # Base name for the istio-init container, used to configure iptables.
    # FIXME: due to a bug in latest proxyv2 image, this code segfaults on circleci
    # so sticking to an old image as we just use the iptables. We need to add this to
    # the release if the bug is not fixed on time
    # https://github.com/istio/istio/issues/19380
    image: tetrate/proxy_init:0.6.6-istio-90c06491b

  # set this to false to disable the post install jobs
  # this setting does not control mTLS. TCC does.
  mtls:
    enabled: false
    auto: true

  outboundTrafficPolicy:
    mode: ALLOW_ANY

  configRootNamespace: istio-config
  defaultConfigVisibilitySettings:
  - '*'
  elasticsearch:
    user: ""
    password: ""
    ssl:
      enabled: true
