pilot:
  traceSampling: 100.0
  enabled: true
  env:
    PILOT_PUSH_THROTTLE: 100
    HTTP10: "true"
    PILOT_ENABLE_MYSQL_FILTER: "true"
    PILOT_SCOPE_GATEWAY_TO_NAMESPACE: "true"
  
gateways:
  enabled: false

security:
  enabled: true
  createMeshPolicy: false

sidecarInjectorWebhook:
  enabled: true

galley:
  enabled: true
  configSink:
    tag: "__TCC__"
    token: ""

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

prometheus:
  enabled: false

tracing:
  enabled: true
  jaeger:
    token: ""
    elasticsearch:
      host: "__HOST__"
      port: 8443
    memory:
      max_traces: 50000
    env:
      SPAN_STORAGE_TYPE: "elasticsearch"
      # Jaeger sends to local envoy which forwards to TCC elastic search.
      ES_SERVER_URLS: "http://127.0.0.1:9200"
oap:
  enabled: true
  tag: "v2.0.e64b50e"
  token: ""
  elasticsearch:
    host: "__HOST__"
    port: 8443

regsource:
  enabled: true
  tag: "__TCC__"
  token: ""

global:
  tcc:
    enabled: true
    host: "__HOST__"
    port: 8443
    tenant: "__TENANT__"
    cluster: "__CLUSTER__"
    environment: "__ENV__"

  hub: "__HUB__"
  tag: "__ISTIO__"
  controlPlaneSecurityEnabled: true
  disablePolicyChecks: true
  enableTracing: true
  configValidation: false
  defaultPodDisruptionBudget:
    enabled: false

  proxy:
    envoyAccessLogService:
      enabled: true
      host: oap.istio-system
      port: 11800

  # set this to false to disable the post install jobs
  # this setting does not control mTLS. TCC does.
  mtls:
    enabled: false

  outboundTrafficPolicy:
    mode: ALLOW_ANY

  configRootNamespace: istio-config
  defaultConfigVisibilitySettings:
  - '*'
