pilot:
  enabled: true

gateways:
  enabled: false

security:
  enabled: true

sidecarInjectorWebhook:
  enabled: true

galley:
  enabled: true
  configSink:
    tag: tcc-v0.5.0
    token: ""

mixer:
  policy:
    enabled: false
  telemetry:
    enabled: false

prometheus:
  enabled: false

oap:
  enabled: true
  tag: "v1.0.build.1581046"
  elasticsearch:
    host: "tcc.visa.com"
    port: 8443

regsource:
  enabled: true
  tag: tcc-v0.5.0
  token: ""

global:
  tcc:
    enabled: true
    host: "tcc.com"
    port: 8443
    tenant: "scooby"
    cluster: "cluster1"
    environment: "dev"

  hub: docker.io/tetrateio
  tag: tcc-v0.5.0-istio
  controlPlaneSecurityEnabled: true
  disablePolicyChecks: true
  enableTracing: false
  # disable validating webhook registration for k8s crds in galley
  # as we dont register crds
  configValidation: false
  defaultPodDisruptionBudget:
    enabled: false

  proxy:
    envoyMetricsService:
      enabled: false
      host: oap.istio-system
      port: 11800
    envoyAccessLogService:
      enabled: true
      host: oap.istio-system
      port: 11800

  mtls:
    enabled: false

  outboundTrafficPolicy:
    mode: ALLOW_ANY

  configRootNamespace: istio-config
  defaultConfigVisibilitySettings:
  - '.'
