apiVersion: traffic.tsb.tetrate.io/v2
kind: ServiceRoute
Metadata:
  organization: {{ orgName }}
  name: {{ serviceRouteName }}
  group: {{ groupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  service: {{ ns }}/{{ hostFQDN }}
  subsets:
  - name: v1
    labels:
      version: v1
    weight: 60
  - name: v2
    labels:
      version: v2
    weight: 30
  - name: v3
    labels:
      version: v3
    weight: 10
