apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsbd-{{ .Release.Namespace }}
  labels:
    app: tsbd
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [  
  "authentication.istio.io",
  "config.istio.io",
  "networking.istio.io",
  "rbac.istio.io",
  "security.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
  # For updating Istio resource statuses
- apiGroups: [
  "authentication.istio.io",
  "config.istio.io",
  "networking.istio.io",
  "rbac.istio.io",
  "security.istio.io"]
  resources: ["*/status"]
  verbs: ["update"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["*"]
- apiGroups: ["extensions","apps"]
  resources: ["deployments"]
  resourceNames: ["istio-galley"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "endpoints", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["deployments/finalizers"]
  resourceNames: ["istio-galley"]
  verbs: ["update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["registry.tetrate.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]  
---
