apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsbd-{{ .Release.Namespace }}
  labels:
    app: tsbd
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [  
  "authentication.istio.io",
  "config.istio.io",
  "networking.istio.io",
  "rbac.istio.io",
  "security.istio.io",
  "install.istio.io" ]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
