apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsbd
  namespace: {{ .Release.Namespace }}
  labels:
    app: tsbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsbd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tsbd
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: tsbd-service-account
      containers:
        - name: tsbd
          image: {{ .Values.hub | default .Values.global.hub }}/tsbd-server:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default .Values.global.imagePullPolicy | default "IfNotPresent"  }}
          command:
          - /usr/local/bin/tsbd-server
          - --tcc-host={{ .Values.global.tcc.host }}:{{ .Values.global.tcc.port }}
          - --cluster={{ .Values.global.tcc.cluster }}
          - --tenant={{ .Values.global.tcc.tenant }}
          - --environment={{ .Values.global.tcc.environment }}
          - --jwt-file=/etc/iam/token
          - --log-output-level=default:info
          - --feature-disable-internal-rbac={{ .Values.disableauthz }}
          volumeMounts:
          - name: tsbd-dir
            mountPath: /etc/tsbd/
          - name: jwt-token
            mountPath: /etc/iam
          ports:
          - containerPort: 9080
          - containerPort: 42422
          resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 12 }}
{{- end }}
      volumes:
      - name: tsbd-dir
        emptyDir: {}
      - name: jwt-token
        secret:
          secretName: tsbd-jwt-token
      - name: mesh-config
        configMap:
          name: istio
