apiVersion: v1
kind: Service
metadata:
  name: tsbd
  namespace: {{ .Release.Namespace }}
  labels:
    app: tsbd
spec:
  ports:
  - port: 443
    targetPort: 9443
    name: https-validation
  - port: 42422
    name: http-monitoring
  - port: 9901
    name: grpc-mcp
  - port: 9080
    name: grpc-regsource
  selector:
    app: tsbd
