version: 2

# Docker environment.
defaults: &defaults
  working_directory: /go/src/istio.io/istio
  docker:
    - image: gcr.io/istio-testing/build-tools:master-2019-11-14T12-01-13
  environment:
    GOPATH: /go
    SKIP_CLEANUP: true

# org context settings. If developing on a clone, please configure:

# DOCKER_USER
# DOCKER_PASS
# HUB: ex istio, costinm (it is not the hub, but the dockerhub org or user)

jobs:
  # This job is triggered via API. expect env vars
  # DOCKER_USER, DOCKER_PASS, HUB, TAG
  dockerpush:
    <<: *defaults
    resource_class: xlarge
    steps:
      - run:
          name: setup ssh
          command: |
            mkdir -p /root/.ssh
            echo -e "\tStrictHostKeyChecking no" >> /root/.ssh/config
            ssh-keyscan github.com >> /root/.ssh/known_hosts
      - checkout
      - run: make sync
      - run: VERSION=${VERSION} make build
      - setup_remote_docker:
          docker_layer_caching: true
      - run: VERSION=${VERSION} make docker.all
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: VERSION=${VERSION} make push

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - test
