---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: tsb-istiocontrolplane
spec:
  values:
    global:
      hub: __HUB__
      tag: __TAG__
      network: Kubernetes
      useMCP: false
      controlPlaneSecurityEnabled: true
      disablePolicyChecks: true
      meshExpansion:
        enabled: true
      proxy:
        accessLogFile: /dev/stdout
        envoyAccessLogService:
          enabled: true
          host: oap.istio-system
          port: "11800"
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      meshNetworks:
        Kubernetes:
          endpoints:
          - fromRegistry: Kubernetes
          gateways:
          - registryServiceName: vmgateway-istio-system.istio-system.svc.cluster.local
          port: 15443
        vm: {}

    gateways:
      istio-ingressgateway:
        labels:
          app: vmgateway
          istio: ingressgateway
        env:
          ISTIO_META_ROUTER_MODE: sni-dnat
          
        ports:
        - port: 15443
          name: tls-k8s-services
        meshExpansionPorts:
        - port: 15012
          targetPort: 15012
          name: tcp-istiod
        - port: 11800
          targetPort: 11800
          name: tcp-oap-grpc
        - port: 9411
          targetPort: 9411
          name: tcp-tracing-grpc    
            
    pilot:
      autoscaleEnabled: false

    tracing:
      enabled: false

  unvalidatedValues:
    global:
      tcc:
        enabled: true
        tenant: __TENANT__
        cluster: __CLUSTER__
        environment: __ENV__

  components:
    egressGateways:
    - name: istio-egressgateway
      enabled: false
    ingressGateways:
    - name: vmgateway
      enabled: true
      namespace: istio-system
    policy:
      enabled: false
    telemetry:
      enabled: false
    pilot:
      k8s:
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: HTTP10
            value: "true"
          - name: PILOT_ENABLE_MYSQL_FILTER
            value: "false"
          - name: PILOT_TRACE_SAMPLING
            value: "1"
          - name: PILOT_PUSH_THROTTLE
            value: "100"
          - name: PILOT_SCOPE_GATEWAY_TO_NAMESPACE
            value: "true"
          - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND
            value: "true"
          - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
            value: "true"
          - name: INJECTION_WEBHOOK_CONFIG_NAME
            value: istio-sidecar-injector
          - name: ISTIOD_ADDR
            value: istiod.istio-system.svc:15012
          - name: PILOT_EXTERNAL_GALLEY
            value: "false"
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
  addonComponents:
    prometheus:
      enabled: false
