---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-operator
  name: tsb-istiocontrolplane
spec:
  profile: tsb
  values:
    global:
      meshNetworks:
        Kubernetes:
          endpoints:
          - fromRegistry: Kubernetes
          gateways:
          - registryServiceName: vmgateway-istio-system.istio-system.svc.cluster.local
          port: 15443
        vm: {}
  components:
    ingressGateways:
    - name: vmgateway
      enabled: true
      namespace: istio-system
      k8s:
        env:
        - name: ISTIO_META_ROUTER_MODE
          value: sni-dnat
        - name: ISTIO_META_NETWORK
          value: Kubernetes
      label:
        app: vmgateway
        tcc: vmgateway
...
