apiVersion: traffic.tsb.tetrate.io/v2
kind: ServiceRoute
Metadata:
  organization: {{ orgName }}
  name: {{ serviceRouteName }}
  group: {{ groupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  service: {{ hostFQDN }}
  subsets:
    - name: v1
      labels:
        version: v1
      weight: 50
    - name: v2
      labels:
        version: v2
      weight: 25
    - name: v3
      labels:
        version: v2
      weight: 25
