apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: bookinfo5-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - bookinfo5.k8s.local
    port:
      name: http
      number: 80
      protocol: HTTP
