apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ gatewayName }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ hostname }}
    port:
      name: http
      number: 80
      protocol: HTTP
