{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-envoy-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: opentelemetry
    component: otel-collector-conf
    chart: {{ template "opentelemetry.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  envoy-config: |
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address: { address: 0.0.0.0, port_value: 50001 }
    static_resources:
      listeners:
      - name: default
        address:
          socket_address: { address: 0.0.0.0, port_value: 9090 }
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/dev/stdout"
              stat_prefix: collector
              codec_type: AUTO
              route_config:
                name: outbound
                virtual_hosts:
                - name: default
                  domains: ['*']
                  routes:
                  - name: outbound
                    match:
                      prefix: "/"
                      headers:
                      - name: ":method"
                        exact_match: "POST"
                    request_headers_to_add:
                    {{- if .Values.token }}
                    - header:
                        key: Authorization
                        value: "Bearer $token"
                    {{- end }}
                    - header:
                        key: tcc-route-target
                        value: otel-collector
                    route: { cluster: tcc }
                  - name: inbound
                    match: { prefix: "/"}
                    route: { cluster: local }
              http_filters:
              - name: envoy.router
      clusters:
      - name: tcc
        connect_timeout: 5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        tls_context: {}
        http2_protocol_options: {}
        hosts:
        - socket_address:
            address: {{ .Values.global.tcc.host }}
            port_value: {{ .Values.global.tcc.port }}
      - name: local
        connect_timeout: 5s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: 0.0.0.0
            port_value: 9091
{{- end }}
