apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-galley
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "galley.name" . }}
    chart: {{ template "galley.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: galley
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      istio: galley
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "galley.name" . }}
        chart: {{ template "galley.chart" . }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}      
        istio: galley
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-galley-service-account
{{- if .Values.global.priorityClassName }}
      priorityClassName: "{{ .Values.global.priorityClassName }}"
{{- end }}
{{- if .Values.configSink }}
      initContainers:
      - name: set-config-link
        image: {{ .Values.global.hub }}/busybox:1.30
        imagePullPolicy: Always
        command: 
        - /bin/sh
        - -c
        - |
          cd /etc/tcc
          echo $PWD
          ls -l
          rm -f config.yaml
          # if config.latest is there, copy it to trigger
          # if not there, its fine - just create trigger file
          # trigger file would be galley's starting config and
          # subsequently moved over to config.latest when configsink-server starts
          cp config.latest trigger 2>/dev/null
          touch trigger
          ln -s trigger config.yaml
          ls -l
        volumeMounts:
        - name: configsink-dir
          mountPath: /etc/tcc/
{{- end }}
      containers:
{{- if .Values.configSink }}
        - name: configsink
          image: {{ .Values.global.hub }}/configsink-server:{{ .Values.configSink.tag }}
          imagePullPolicy: Always
          command: 
          - /usr/local/bin/configsink-server
          - --tcc-host={{ .Values.global.tcc.host }}:{{ .Values.global.tcc.port }}
          - --cluster={{ .Values.global.tcc.cluster }}
          - --tenant={{ .Values.global.tcc.tenant }}
          - --environment={{ .Values.global.tcc.environment }}
          volumeMounts:
          - name: configsink-dir
            mountPath: /etc/tcc/
{{- end }}
        - name: galley
{{- if contains "/" .Values.image }}
          image: "{{ .Values.image }}"
{{- else }}
          image: "{{ .Values.global.hub }}/{{ .Values.image }}:{{ .Values.global.tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
          - containerPort: 443
          - containerPort: {{ .Values.global.monitoringPort }}
          - containerPort: 9901
          command:
          - /usr/local/bin/galley
          - server
          - --meshConfigFile=/etc/mesh-config/mesh
          - --livenessProbeInterval=1s
          - --livenessProbePath=/healthliveness
          - --readinessProbePath=/healthready
          - --readinessProbeInterval=1s
          - --deployment-namespace={{ .Release.Namespace }}
{{- if $.Values.global.controlPlaneSecurityEnabled}}
          - --insecure=false
{{- else }}
          - --insecure=true
{{- end }}
{{- if not $.Values.global.useMCP }}
          - --enable-server=false
{{- end }}
          - --validation-webhook-config-file
          - /etc/config/validatingwebhookconfiguration.yaml
          - --monitoringPort={{ .Values.global.monitoringPort }}
{{- if $.Values.global.logging.level }}
          - --log_output_level={{ $.Values.global.logging.level }}
{{- end}}
{{- if .Values.configSink }}
          - --configPath=/etc/tcc/config.yaml
          - --resyncPeriod=1s
{{- end }}
          volumeMounts:
{{- if .Values.configSink }}
          - name: configsink-dir
            mountPath: /etc/tcc/
{{- end }}
          - name: certs
            mountPath: /etc/certs
            readOnly: true
          - name: config
            mountPath: /etc/config
            readOnly: true
          - name: mesh-config
            mountPath: /etc/mesh-config
            readOnly: true
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/galley
                - probe
                - --probe-path=/healthliveness
                - --interval=10s
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/galley
                - probe
                - --probe-path=/healthready
                - --interval=10s
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 12 }}
{{- else }}
{{ toYaml .Values.global.defaultResources | indent 12 }}
{{- end }}
      volumes:
{{- if .Values.configSink }}
      - name: configsink-dir
        persistentVolumeClaim:
          claimName: configsink-data
{{- end }}
      - name: certs
        secret:
          secretName: istio.istio-galley-service-account
      - name: config
        configMap:
          name: istio-galley-configuration
      - name: mesh-config
        configMap:
          name: istio
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
      {{- else if .Values.global.defaultTolerations }}
      tolerations:
{{ toYaml .Values.global.defaultTolerations | indent 6 }}
      {{- end }}
