#
# Copyright (c) Tetrate, Inc 2019 All Rights Reserved.
#
# Add your app as service to this sidecar docker-compose. Note: proxy sidecar
# and node-agent runs on host network mode, so they can be routable. Also, it
# is assumed that app is reachable on 127.0.0.1:appPort
#
version: '3'
services:
  node-agent:
    container_name: node-agent
    image: {{ .Values.global.hub }}/node-agent:{{ .Values.global.istio.tag }}
    command: |
        --ca-address "{{ .Values.global.vmgateway.host }}:8060"
        --platform vm
    volumes:
      - {{ .Values.global.sidecar.certPath }}:/etc/certs:rw
{{- if $.Values.global.sidecar.hostModeNetwork}}
    network_mode: host
{{- end }}
    extra_hosts:
    - "istio-citadel.{{.Values.global.istio.namespace}}.svc.cluster.local:{{ .Values.global.vmgateway.host }}"
    restart: unless-stopped

  istio-proxy:
    container_name: istio-proxy
    image: {{ .Values.global.hub }}/proxyv2:{{ .Values.global.istio.tag }}
    command: |
      proxy sidecar
      --discoveryAddress "istio-pilot.istio-system.svc.cluster.local:15011"
      --statusPort 15020 --applicationPorts {{ .Values.global.sidecar.appPort }}
      --parentShutdownDuration 1m0s --dnsRefreshRate 300s --connectTimeout 10s
      --concurrency 2 --controlPlaneAuthPolicy MUTUAL_TLS
      --envoyAccessLogService '{"address":"oap.istio-system.svc.cluster.local:11800","tlsSettings":{"mode":"DISABLE","subjectAltNames":[]},"tcpKeepalive":{"interval":"10s","probes":3,"time":"10s"}}'
      --zipkinAddress zipkin.istio-system.svc.cluster.local:9411
    environment:
      - ISTIO_METAJSON_LABELS={"app":"{{ .Values.global.sidecar.serviceDefinition }}","catalog.tetrate.io/serviceName":"{{ .Values.global.sidecar.serviceDefinition }}.{{ .Values.global.sidecar.appNs }}"}
      - ISTIO_META_POD_PORTS=[{"containerPort":{{ .Values.global.sidecar.appPort }},"protocol":"TCP"}]
      - POD_NAME=sidecar.{{ .Values.global.sidecar.serviceDefinition }}
      - POD_NAMESPACE={{ .Values.global.sidecar.appNs }}
      - SERVICE_ACCOUNT=default
      - ISTIO_META_POD_NAME=sidecar.{{ .Values.global.sidecar.serviceDefinition }}
      - ISTIO_META_CONFIG_NAMESPACE={{ .Values.global.sidecar.appNs }}
      - ISTIO_META_TSB_TENANT={{ .Values.global.tcc.tenant }}
      - ISTIO_META_TSB_CLUSTER={{ .Values.global.tcc.cluster }}
      - ISTIO_META_TSB_ENVIRONMENT={{ .Values.global.tcc.env }}
      - ISTIO_META_TSB_APPLICATION={{ .Values.global.sidecar.appId }}
      - ISTIO_META_NETWORK="vm"
    extra_hosts:
    - "istio-pilot.istio-system.svc.cluster.local:{{ .Values.global.vmgateway.host }}"
    - "oap.istio-system.svc.cluster.local:{{ .Values.global.vmgateway.host }}"
    - "zipkin.istio-system.svc.cluster.local:{{ .Values.global.vmgateway.host }}"
    ports:
    - "15090:15090"
    volumes:
      - {{ .Values.global.sidecar.certPath }}:/etc/certs:rw
{{- if $.Values.global.sidecar.hostModeNetwork}}
    network_mode: host
{{- end }}
    restart: unless-stopped
