apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    tsb.tetrate.io/gatewayGroup: {{ gatewayGroupName }}
    tsb.tetrate.io/tenant: {{ tenantName }}
    tsb.tetrate.io/organization: {{ orgName }}
    tsb.tetrate.io/workspace: {{ workspaceName }}
  name: {{ gatewayName }}
  namespace: {{ ns }}
spec:
  selector:
    app: tsb-gateway-{{ ns }}
  servers:
  - hosts:
    - {{ ns }}/{{ hostFQDN }}
    port:
      name: https-bookinfo-direct
      number: 8443
      protocol: HTTPS
    tls:
      credentialName: {{ gwSecretName }}
      mode: SIMPLE
