apiVersion: apps/v1
kind: Deployment
metadata:
  name: oap-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: oap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oap
  template:
    metadata:
      labels:
        app: oap
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: oap-service-account
      initContainers:
      - name: copy-raw-config
        image: {{ .Values.global.hub }}/spm-user:{{ .Values.tag }}
        command: ['/bin/sh']
        args: ['-c', 'cp /skywalking/config/* /config']
        volumeMounts:
          - name: config
            mountPath: /config
      - name: override-config
        image: {{ .Values.global.hub }}/envsubst:v1.0
        command: ['/bin/sh']
        args: ['-c', 'for file in $(ls -A /tmpl); do envsubst < /tmpl/$file > /config/$file; done']
        volumeMounts:
          - name: tmpl
            mountPath: /tmpl
          - name: config
            mountPath: /config
        envFrom:
        - secretRef:
            name: oap-token
      containers:
      - name: oap
        image: {{ .Values.global.hub }}/spm-user:{{ .Values.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: rest
        - containerPort: 1234
          name: http-monioring
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: JAVA_OPTS
          value: -Xmx4096M -Dmode=no-init
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        volumeMounts:
        - mountPath: /skywalking/config
          name: config
      - name: istio-proxy
{{- if contains "/" .Values.global.proxy.image }}
        image: "{{ .Values.global.proxy.image }}"
{{- else }}
        image: "{{ .Values.global.hub }}/{{ .Values.global.proxy.image }}:{{ .Values.global.tag }}"
{{- end }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: [ "/usr/local/bin/envoy" ]
        args:
        - -c
        - /etc/envoy/envoy.yaml
        - --service-cluster
        - envoy-proxy
        ports:
        - containerPort: 50001
        - containerPort: 9200
        volumeMounts:
        - mountPath: /etc/envoy/
          name: config
      volumes:
      - name: tmpl
        configMap:
          name: oap-config
      - name: config
        emptyDir: {}
