apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ gatewayGroupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ gatewayGroupName }}
  namespaceSelector:
    names:
    - {{ clusterName }}/{{ namespaces['product'] or namespaces }}
  configMode: {{ mode }}
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ trafficGroupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ trafficGroupName }}
  namespaceSelector:
    names:
    - {{ clusterName }}/{{ namespaces['reviews'] or namespaces }}
  configMode: {{ mode }}
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  organization: {{ orgName }}
  name: {{ securityGroupName }}
  workspace: {{ workspaceName }}
  tenant: {{ tenantName }}
spec:
  displayName: {{ securityGroupName }}
  namespaceSelector:
    names:
    {% if namespaces is mapping -%}
    {% for ns in namespaces %}- {{ clusterName }}/{{ namespaces[ns] }}
    {% endfor -%}
    {% else -%}
    - {{ clusterName }}/{{ namespaces }}
    {% endif -%}
  configMode: {{ mode }}
