# an array of configuration
config:
  - replicas: 2 # how many times we want to replicate the same bookinfo configuration in cluster 
    organisation: "tetrate"
    clusterName: "demo"
    mode: "bridged" # possible values: `bridged` or `direct`
    # for selecting the node ip to be used to send traffic with trafficgen pod
    trafficGenIPType: "internal" # possible values: `external` or `internal`
