name: Create Release
# should run for [0-9]+.[0-9]+.0
# but should be automated, using github.event.inputs.tag doesnt make sense
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        default: 1.0.0
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: "refs/tags/${{ github.event.inputs.tag }}"

      - name: Create Release Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release-${{ github.event.inputs.tag }}

      - name: Create Tetrate Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: tetrate-${{ github.event.inputs.tag }}
