name: e2e-tests

on:
  push:
    tags:
      - 'test-*'

env:
  HUB: ${{ secrets.TEST_HUB }}

jobs:
  create-test-images:
    name: create-test-images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker-login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.HUB }}
          username: ${{ secrets.TEST_HUB_USER }}
          password: ${{ secrets.TEST_HUB_PASS }}
      
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/}
        shell: bash

      - name: build and push images
        # TODO: Hack Alert https://github.com/actions/runner/issues/241
        shell: 'script -q -e -c "bash {0}"'
        run: |
          make docker push
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}

  eks-e2e-test:
    ## TODO: temporarily disabling it till credentials are set
    if: ${{ false }}
    name: eks-e2e-test
    runs-on: ubuntu-latest
    needs: [create-test-images]

    strategy:
      matrix:
        version: [1.18]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: aws-config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION  }}

      - name: set up go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/}
        shell: bash

      - name: eks-cluster-create
        run: bash ./tetrateci/create_eks_cluster.sh
        env:
          VER: ${{ matrix.version }}

      - name: integration-tests
        run: |
          go test -tags=integ ./tests/integration/operator/...  -istio.test.skipVM true -p 1  -test.v
          go test -tags=integ ./tests/integration/helm/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ -timeout 30m -run='TestEmptyCluster|TestFileOnly|TestDirectoryWithoutRecursion|TestDirectoryWithRecursion|TestInvalidFileError|TestJsonInputFile|TestJsonOutput|TestKubeOnly|TestFileAndKubeCombined|TestAllNamespaces|TestTimeout|TestErrorLine|TestWait|TestVersion|TestDescribe|TestAddToAndRemoveFromMesh|TestProxyConfig|TestProxyStatus|TestAuthZCheck|TestLocality|TestMain|TestMirroring|TestMirroringExternalService|TestTproxy|TestRevisionedUpgrade|TestValidation|TestEnsureNoMissingCRDs|TestWebhook' ./tests/integration/pilot/ -istio.test.skipVM true -p 1 -test.v 
          go test -tags=integ ./tests/integration/pilot/analysis/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ ./tests/integration/pilot/cni/... -istio.test.skipVM true -p 1 -test.v 
          go test -tags=integ ./tests/integration/pilot/revisions/... -istio.test.skipVM true -p 1 -test.v 
          go test -tags=integ -timeout 30m -run='TestStatsFilter|TestStatsTCPFilter|TestSetup|TestIstioctlMetrics|TestTcpMetric|TestStatsFilter|TestWASMTcpMetric|TestWasmStatsFilter|TestMain|TestCustomizeMetrics'  ./tests/integration/telemetry/stats/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/ca_custom_root/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/chiron/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/file_mounted_certs/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/filebased_tls_origination/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/mtls_first_party_jwt/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/mtlsk8sca/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/sds_egress/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/sds_tls_origination/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/webhook/... -istio.test.skipVM true -p 1 -test.v
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}

      - name: eks-cluster-delete
        if: always()
        run: bash ./tetrateci/cleanup_eks_cluster.sh
        env:
          VER: ${{ matrix.version }}
  
  gke-e2e-test:
    name: gke-e2e-test
    runs-on: ubuntu-latest
    needs: [create-test-images]

    strategy:
      matrix:
        version: ["1.17.13-gke.2600"]
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: set up go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/}
        shell: bash

      - name: gke-cluster-create
        run: bash ./tetrateci/create_gke_cluster.sh
        env:
          VER: ${{ matrix.version }}

      - name: integration-tests
        run: |
          go test -tags=integ ./tests/integration/operator/...  -istio.test.skipVM true -p 1  -test.v
          go test -tags=integ ./tests/integration/helm/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ -timeout 30m -run='TestEmptyCluster|TestFileOnly|TestDirectoryWithoutRecursion|TestDirectoryWithRecursion|TestInvalidFileError|TestJsonInputFile|TestJsonOutput|TestKubeOnly|TestFileAndKubeCombined|TestAllNamespaces|TestTimeout|TestErrorLine|TestWait|TestVersion|TestDescribe|TestAddToAndRemoveFromMesh|TestProxyConfig|TestProxyStatus|TestAuthZCheck|TestLocality|TestMain|TestMirroring|TestMirroringExternalService|TestTproxy|TestValidation|TestEnsureNoMissingCRDs|TestWebhook' ./tests/integration/pilot/ -istio.test.skipVM true -p 1 -test.v 
          go test -tags=integ ./tests/integration/pilot/analysis/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ ./tests/integration/pilot/revisions/... -istio.test.skipVM true -p 1 -test.v
          # Overy CNI Parameters for GCP : https://github.com/tetratelabs/getistio/issues/76
          pip install pyyaml --user && ./tetrateci/gen_iop.py
          go test -count=1 -tags=integ ./tests/integration/pilot/cni/...  -istio.test.kube.helm.iopFile $(pwd)/tetrateci/iop-gke-integration.yml  -test.v
          go test -tags=integ -timeout 30m -run='TestStatsFilter|TestStatsTCPFilter|TestSetup|TestIstioctlMetrics|TestTcpMetric|TestStatsFilter|TestWASMTcpMetric|TestWasmStatsFilter|TestMain|TestCustomizeMetrics'  ./tests/integration/telemetry/stats/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/ca_custom_root/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/file_mounted_certs/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/filebased_tls_origination/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/mtls_first_party_jwt/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/mtlsk8sca/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/sds_egress/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/sds_tls_origination/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/webhook/... -istio.test.skipVM true -p 1 -test.v
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}

      - name: gke-cluster-delete
        if: always()
        run: bash ./tetrateci/cleanup_gke_cluster.sh
        env:
          VER: ${{ matrix.version }}

  aks-e2e-test:
    ## TODO: temporarily disabling it till credentials are set
    if: ${{ false }}
    name: aks-e2e-test
    runs-on: ubuntu-latest
    needs: [create-test-images]

    strategy:
      matrix:
        version: [1.18.10]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      - name: set up go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/}
        shell: bash

      - name: aks-cluster-create
        run: bash ./tetrateci/create_aks_cluster.sh
        env:
          VER: ${{ matrix.version }}
          RESOURCE: ${{ secrets.AZURE_RESOURCE }}

      - name: integration-tests
        run: |
          go test -tags=integ ./tests/integration/operator/...  -istio.test.skipVM true -p 1  -test.v
          go test -tags=integ ./tests/integration/helm/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ -timeout 30m -run='TestEmptyCluster|TestFileOnly|TestDirectoryWithoutRecursion|TestDirectoryWithRecursion|TestInvalidFileError|TestJsonInputFile|TestJsonOutput|TestKubeOnly|TestFileAndKubeCombined|TestAllNamespaces|TestTimeout|TestErrorLine|TestWait|TestVersion|TestDescribe|TestAddToAndRemoveFromMesh|TestProxyConfig|TestProxyStatus|TestAuthZCheck|TestLocality|TestMain|TestMirroring|TestMirroringExternalService|TestTproxy|TestValidation|TestEnsureNoMissingCRDs|TestWebhook' ./tests/integration/pilot/ -istio.test.skipVM true -p 1 -test.v 
          go test -tags=integ ./tests/integration/pilot/analysis/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ ./tests/integration/pilot/revisions/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ -timeout 30m -run='TestStatsFilter|TestStatsTCPFilter|TestSetup|TestIstioctlMetrics|TestTcpMetric|TestStatsFilter|TestWASMTcpMetric|TestWasmStatsFilter|TestMain|TestCustomizeMetrics'  ./tests/integration/telemetry/stats/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/ca_custom_root/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/file_mounted_certs/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/filebased_tls_origination/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/mtls_first_party_jwt/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/mtlsk8sca/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/sds_egress/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/sds_tls_origination/... -istio.test.skipVM true -p 1 -test.v
          go test -tags=integ  ./tests/integration/security/webhook/... -istio.test.skipVM true -p 1 -test.v
        env:
          TAG: ${{ steps.get_tag.outputs.TAG }}

      - name: aks-cluster-delete
        if: always()
        run: bash ./tetrateci/cleanup_aks_cluster.sh
        env:
          VER: ${{ matrix.version }}
          RESOURCE: ${{ secrets.AZURE_RESOURCE }}
    
  create-new-tag:
    name: create-new-tag
    runs-on: ubuntu-latest
    needs: [eks-e2e-test, gke-e2e-test, aks-e2e-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/test-/}
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG }}
          release_name: Tetrate Istio 
          draft: false
          prerelease: false

  make_release:    
    needs: [create-new-tag]

    name: release-builder-run
    runs-on: ubuntu-latest
    env:
      HUB: ${{ secrets.DEPLOY_HUB }}

    steps:
      - name: Checkout tetrate branch
        uses: actions/checkout@v2

      - name: Login to Bintray
        uses: docker/login-action@v1
        with:
          registry: ${{ env.HUB }}
          username: ${{ secrets.BINTRAY_USER }}
          password: ${{ secrets.BINTRAY_API_KEY }}

      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\/test-/}
        shell: bash

      - name: run release builder
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          TAG: ${{ steps.get_tag.outputs.TAG }}
          BINTRAY_API: ${{ secrets.BINTRAY_ARCHIVE_API }}
        # not using the official build container 
        run: ./tetrateci/create_istio_release.sh
