name: Make a release

on:
  workflow_dispatch: 
    inputs:
      tag:
        description: Manual Tag
        required: true
      type:
        description: Build Type [fips or leave empty]
        required: true
        default: ""

jobs:
  make_release:    
    name: release-builder-run
    runs-on: ubuntu-latest
    env:
      HUB: ${{ secrets.DEPLOY_HUB }}

    steps:
      - name: Checkout to choosen tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Login to Bintray
        uses: docker/login-action@v1
        with:
          registry: ${{ env.HUB }}
          username: ${{ secrets.BINTRAY_USER }}
          password: ${{ secrets.BINTRAY_API_KEY }}

      - name: set up go 1.15
        uses: actions/setup-go@v1
        # cause we setup go ourselves otherwise
        if: ${{ !contains(github.event.ref, 'fips') }}
        with:
          go-version: 1.15

      - name: Run release builder
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          TAG: ${{ github.event.inputs.tag }}
          BINTRAY_API: ${{ secrets.BINTRAY_ARCHIVE_API }}
          BUILD: ${{ github.event.inputs.type }}
        run: bash ./tetrateci/create_istio_release.sh