name: Update the release branches
on:
  push:
    branches:
      - release-[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: ${{ steps.extract_branch.outputs.branch }}.0-tetrate
        github_token: ${{ secrets.GITHUB_TOKEN }}

