name: Sync fork

on:
  schedule:
    - cron:  '0 0 * * *' 

  workflow_dispatch: 

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout tetrate
      uses: actions/checkout@v2
      with:
        ref: tetrate 
        token: {{ secrets.PAT }}

    - name: Sync the tags
      run: bash ./tetrateci/fetch_all_tags.sh