name: Update the release branches
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[1-9][0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Extract tag
      shell: bash
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tag/} | rev | cut -d . -f2- | rev)"
      id: extract_tag

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: release-${{ steps.extract_tag.outputs.tag }}
        destination_branch: tetrate-${{ steps.extract_tag.outputs.tag }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

