name: Update the release branches
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[1-9][0-9]*'
  workflow_dispatch:
    inputs:
        tag:
          description: Tag
          default: 1.0.0
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "refs/tags/${{ github.event.inputs.tag }}"

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: release-${{ github.event.inputs.tag }}
        destination_branch: tetrate-${{ github.event.inputs.tag }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

