apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: {{ productns }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: {{ reviewsns }}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: {{ ratingsns }}
---
