apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: {{ saName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ targetNS }}
  name: trafficgen-service-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trafficgen-service-reader-binding
  namespace: {{ targetNS }}
subjects:
- kind: ServiceAccount
  name: {{ saName }}
  namespace: {{ clientNS }}
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: ""

